import { Inter } from "next/font/google";
import "./globals.css";
import '../public/css/all.min.css';
import '../public/css/animate.css';
import '../public/css/bootstrap.min.css';
import '../public/css/glyphter.css'; // Changed to lowercase
import '../public/css/magnific-popup.css';
import '../public/css/main.min.css';
import '../public/css/nice-select.css';
import '../public/css/slick.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Blood Test",
  description: "Generated by AI Blood Test",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
